language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3.5"
install:
  - "pip install -r requirements-tests.txt"
  - "pip install ."
script: 
  - "py.test --cov-fail-under=50 --cov=shentry --cov-report=term-missing tests/"
env:
  - TZ=UTC
