language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - "pip install -r requirements-tests.txt"
  - "pip install ."
script: 
  - "py.test --cov-fail-under=50 --cov=shentry --cov-report=term-missing tests/"
  - "if python -c 'import sys; exit(1 if sys.version_info < (2, 7) else 0)' ; then flake8 shentry.py ; else echo 'flake8 is broken on py26'; fi
env:
  - TZ=UTC
