name: 'CI'

on:
  push:
    branches: [master]
  pull_request:

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: install dependencies
        run: make install
      - name: lint with flake8
        run: make lint
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pythonversion: ['3.7', '3.8', '3.9', '3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v3
      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.pythonversion }}
      - name: install dependencies
        run: make install
      - name: test with pytest
        run: make coverage
      - name: Coveralls
        if: github.ref == 'refs/heads/master'
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: './coverage.lcov'
