name: 'CI'

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: install dependencies
        run: python -m pip install flake8
      - name: lint with flake8
        run: flake8 --statistics shentry.py
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pythonversion: ['2.6', '2.7', '3.5', '3.6', '3.7', '3.8', '3.9', 'pypy-2.7', 'pypy-3.6']
    steps:
      - uses: actions/checkout@v2
      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.pythonversion }}
      - name: install dependencies
        run: "python -m pip install -r requirements-tests.txt -e ."
      - name: test with pytest
        run: py.test --cov-fail-under=50 --cov=shentry --cov-report=term-missing tests/
